laggings:
chestplate:
helmet:
boots:
block:
laggings1:
chestplate1:
helmet1:
boots1:
block1:
laggings2:
chestplate2:
helmet2:
boots2:
block2:
laggings3:
chestplate3:
helmet3:
boots3:
block3:
laggings4:
chestplate4:
helmet4:
boots4:
block4:
laggings5:
chestplate5:
helmet5:
boots5:
block5:
laggings6:
chestplate6:
helmet6:
boots6:
block6:
laggings7:
chestplate7:
helmet7:
boots7:
block7:
laggings8:
chestplate8:
helmet8:
boots8:
block8:
laggings9:
chestplate9:
helmet9:
boots9:
block9:
laggings10:
chestplate10:
helmet10:
boots10:
block10:
