name: StepForArmor
main: Main
version: 1
api: [1.0.0]

load: POSTWORLD
authors: [SwagBoy43]
description: step on block to get armor

commands:
    stepforarmor:
        desctiption: "Main StepForArmor Command"
        usage: "/banhammer <1-11> <HelemtID> <ChestPlateID> <LaggingsID> <BootsID> <BlockID>"
        aiases: [sfa]
