#MinePlus Settings
true1: true
mine1: 1
fire: 5
true2: true
mine2: 2
heal: 10
true3: true
mine3: 3
attak: 10
true5: true
mine5: 4
true6: 5
mine6: 5
kick: you have stepped on a mine
true7: true
mine7: 6
sendMessage: you have stepped on a mine
true8: true
mine8: 7
true9: true
mine9: 12
true10: true
mine10: 13
true11: true
mine11: 14
true12: true
mine12: 15
x: 0
y: 0
z: 0
true13: true
mine13: 16
item: 265
true14: true
mine14: 17
true15: true
mine15: 18
high: 276
