name: PvpPro
main: swagking\PvpPro\Main
version: 1.1.0
api: 1.0.0
author: Swagking47
description: a plugin to control PVP
website: https://github.com/swagking47/1.0.0-plugins/tree/master/PvpPro

commands:
 PVP:
  description: "to set the PVP mode"
  usage: "/PVPpro ON or OFF"
  permission: PVPpro.command.PVPpro
