name: invulnerability
main: swagboy47\Invulnerability\Main
version: 1.0.0
api: [1.0.0]

load: POSTWORLD
authors: [SwagBoy47]
description: get no damage!

commands:
    i:
        description: "enables and disables invulnerability!"
        usage: "/i <player>"
        permission: op
